// Generated by tools/generate_mp2_native.py from compiler UMP2 TensorIR; do not edit.
#pragma once
#include <algorithm>
#include <cmath>
#include <cstddef>
#include <stdexcept>
#include <vector>
namespace generativeqc::mp2::generated {
using Ump2Run = void (*)(double, double, double, double, double, double, double*);
struct Ump2CpuPlan {
  Ump2Run run;
  std::size_t numeric_bytes;
  const char* equation_hash;
};
// TensorIR equation 3941fc92696729f5febb65057fcfccdfd5b68f57115c2c3d9883f26a401f0356
inline void ump2_tile_alpha_alpha(const double* const* inputs, double* const* outputs) {
  const double* v0 = inputs[0];
  if (!v0) throw std::invalid_argument("null tensor input");
  for (size_t z = 0; z < 1; ++z)
    if (!std::isfinite(v0[z])) throw std::runtime_error("nonfinite TensorIR input");
  const double* v1 = inputs[1];
  if (!v1) throw std::invalid_argument("null tensor input");
  for (size_t z = 0; z < 1; ++z)
    if (!std::isfinite(v1[z])) throw std::runtime_error("nonfinite TensorIR input");
  const double* v2 = inputs[2];
  if (!v2) throw std::invalid_argument("null tensor input");
  for (size_t z = 0; z < 1; ++z)
    if (!std::isfinite(v2[z])) throw std::runtime_error("nonfinite TensorIR input");
  const double* v3 = inputs[3];
  if (!v3) throw std::invalid_argument("null tensor input");
  for (size_t z = 0; z < 1; ++z)
    if (!std::isfinite(v3[z])) throw std::runtime_error("nonfinite TensorIR input");
  const double* v4 = inputs[4];
  if (!v4) throw std::invalid_argument("null tensor input");
  for (size_t z = 0; z < 1; ++z)
    if (!std::isfinite(v4[z])) throw std::runtime_error("nonfinite TensorIR input");
  const double* v5 = inputs[5];
  if (!v5) throw std::invalid_argument("null tensor input");
  for (size_t z = 0; z < 1; ++z)
    if (!std::isfinite(v5[z])) throw std::runtime_error("nonfinite TensorIR input");
  std::vector<double> storage6(1);
  double* v6 = storage6.data();
  for (size_t z = 0; z < 1; ++z) v6[z] = v1[((z / 1) % 1) * 1];
  for (size_t z = 0; z < 1; ++z)
    if (!std::isfinite(v6[z])) throw std::runtime_error("nonfinite TensorIR broadcast");
  std::vector<double> storage7(1);
  double* v7 = storage7.data();
  for (size_t z = 0; z < 1; ++z)
    v7[z] = (0x1.0000000000000p+0 * v5[z]) + (-0x1.0000000000000p+0 * v3[z]);
  for (size_t z = 0; z < 1; ++z)
    if (!std::isfinite(v7[z])) throw std::runtime_error("nonfinite TensorIR add");
  std::vector<double> storage8(1);
  double* v8 = storage8.data();
  for (size_t z = 0; z < 1; ++z) v8[z] = v0[((z / 1) % 1) * 1];
  for (size_t z = 0; z < 1; ++z)
    if (!std::isfinite(v8[z])) throw std::runtime_error("nonfinite TensorIR broadcast");
  std::vector<double> storage9(1);
  double* v9 = storage9.data();
  for (size_t z = 0; z < 1; ++z) v9[z] = v4[((z / 1) % 1) * 1];
  for (size_t z = 0; z < 1; ++z)
    if (!std::isfinite(v9[z])) throw std::runtime_error("nonfinite TensorIR broadcast");
  std::vector<double> storage10(1);
  double* v10 = storage10.data();
  for (size_t z = 0; z < 1; ++z) v10[z] = v2[((z / 1) % 1) * 1];
  for (size_t z = 0; z < 1; ++z)
    if (!std::isfinite(v10[z])) throw std::runtime_error("nonfinite TensorIR broadcast");
  std::vector<double> storage11(1);
  double* v11 = storage11.data();
  for (size_t z = 0; z < 1; ++z)
    v11[z] = (0x1.0000000000000p+0 * v9[z]) + (0x1.0000000000000p+0 * v10[z]) +
             (-0x1.0000000000000p+0 * v6[z]) + (-0x1.0000000000000p+0 * v8[z]);
  for (size_t z = 0; z < 1; ++z)
    if (!std::isfinite(v11[z])) throw std::runtime_error("nonfinite TensorIR add");
  std::vector<double> storage12(1);
  double* v12 = storage12.data();
  for (size_t z = 0; z < 1; ++z)
    if (v11[z] == 0) throw std::runtime_error("zero tensor denominator");
  for (size_t z = 0; z < 1; ++z) v12[z] = v7[z] / v11[z];
  for (size_t z = 0; z < 1; ++z)
    if (!std::isfinite(v12[z])) throw std::runtime_error("nonfinite TensorIR divide");
  std::vector<double> storage13(1);
  double* v13 = storage13.data();
  for (size_t z = 0; z < 1; ++z) v13[z] = v12[z] * v7[z];
  for (size_t z = 0; z < 1; ++z)
    if (!std::isfinite(v13[z])) throw std::runtime_error("nonfinite TensorIR multiply");
  std::vector<double> storage14(1);
  double* v14 = storage14.data();
  for (size_t q = 0; q < 1; ++q) {
    v14[0] += v13[q];
    if (!std::isfinite(v14[0])) throw std::runtime_error("nonfinite tensor reduction");
  }
  for (size_t z = 0; z < 1; ++z)
    if (!std::isfinite(v14[z])) throw std::runtime_error("nonfinite TensorIR reduce");
  std::vector<double> storage15(1);
  double* v15 = storage15.data();
  for (size_t z = 0; z < 1; ++z) v15[z] = (0x1.0000000000000p-2 * v14[z]);
  for (size_t z = 0; z < 1; ++z)
    if (!std::isfinite(v15[z])) throw std::runtime_error("nonfinite TensorIR add");
  std::copy_n(v15, 1, outputs[0]);
}

inline void ump2_run_alpha_alpha(double g, double x, double ei, double ej, double ea, double eb,
                                 double* out) {
  const double* inputs[] = {&eb, &ea, &ej, &x, &ei, &g};
  double* outputs[] = {out};
  ump2_tile_alpha_alpha(inputs, outputs);
}
// TensorIR equation 615228b15a06c1219a3daf3e54a4a0ab5ebb50cb73c418745f057f33a47eeab7
inline void ump2_tile_beta_beta(const double* const* inputs, double* const* outputs) {
  const double* v0 = inputs[0];
  if (!v0) throw std::invalid_argument("null tensor input");
  for (size_t z = 0; z < 1; ++z)
    if (!std::isfinite(v0[z])) throw std::runtime_error("nonfinite TensorIR input");
  const double* v1 = inputs[1];
  if (!v1) throw std::invalid_argument("null tensor input");
  for (size_t z = 0; z < 1; ++z)
    if (!std::isfinite(v1[z])) throw std::runtime_error("nonfinite TensorIR input");
  const double* v2 = inputs[2];
  if (!v2) throw std::invalid_argument("null tensor input");
  for (size_t z = 0; z < 1; ++z)
    if (!std::isfinite(v2[z])) throw std::runtime_error("nonfinite TensorIR input");
  const double* v3 = inputs[3];
  if (!v3) throw std::invalid_argument("null tensor input");
  for (size_t z = 0; z < 1; ++z)
    if (!std::isfinite(v3[z])) throw std::runtime_error("nonfinite TensorIR input");
  const double* v4 = inputs[4];
  if (!v4) throw std::invalid_argument("null tensor input");
  for (size_t z = 0; z < 1; ++z)
    if (!std::isfinite(v4[z])) throw std::runtime_error("nonfinite TensorIR input");
  const double* v5 = inputs[5];
  if (!v5) throw std::invalid_argument("null tensor input");
  for (size_t z = 0; z < 1; ++z)
    if (!std::isfinite(v5[z])) throw std::runtime_error("nonfinite TensorIR input");
  std::vector<double> storage6(1);
  double* v6 = storage6.data();
  for (size_t z = 0; z < 1; ++z)
    v6[z] = (0x1.0000000000000p+0 * v2[z]) + (-0x1.0000000000000p+0 * v1[z]);
  for (size_t z = 0; z < 1; ++z)
    if (!std::isfinite(v6[z])) throw std::runtime_error("nonfinite TensorIR add");
  std::vector<double> storage7(1);
  double* v7 = storage7.data();
  for (size_t z = 0; z < 1; ++z) v7[z] = v3[((z / 1) % 1) * 1];
  for (size_t z = 0; z < 1; ++z)
    if (!std::isfinite(v7[z])) throw std::runtime_error("nonfinite TensorIR broadcast");
  std::vector<double> storage8(1);
  double* v8 = storage8.data();
  for (size_t z = 0; z < 1; ++z) v8[z] = v4[((z / 1) % 1) * 1];
  for (size_t z = 0; z < 1; ++z)
    if (!std::isfinite(v8[z])) throw std::runtime_error("nonfinite TensorIR broadcast");
  std::vector<double> storage9(1);
  double* v9 = storage9.data();
  for (size_t z = 0; z < 1; ++z) v9[z] = v0[((z / 1) % 1) * 1];
  for (size_t z = 0; z < 1; ++z)
    if (!std::isfinite(v9[z])) throw std::runtime_error("nonfinite TensorIR broadcast");
  std::vector<double> storage10(1);
  double* v10 = storage10.data();
  for (size_t z = 0; z < 1; ++z) v10[z] = v5[((z / 1) % 1) * 1];
  for (size_t z = 0; z < 1; ++z)
    if (!std::isfinite(v10[z])) throw std::runtime_error("nonfinite TensorIR broadcast");
  std::vector<double> storage11(1);
  double* v11 = storage11.data();
  for (size_t z = 0; z < 1; ++z)
    v11[z] = (0x1.0000000000000p+0 * v10[z]) + (0x1.0000000000000p+0 * v9[z]) +
             (-0x1.0000000000000p+0 * v7[z]) + (-0x1.0000000000000p+0 * v8[z]);
  for (size_t z = 0; z < 1; ++z)
    if (!std::isfinite(v11[z])) throw std::runtime_error("nonfinite TensorIR add");
  std::vector<double> storage12(1);
  double* v12 = storage12.data();
  for (size_t z = 0; z < 1; ++z)
    if (v11[z] == 0) throw std::runtime_error("zero tensor denominator");
  for (size_t z = 0; z < 1; ++z) v12[z] = v6[z] / v11[z];
  for (size_t z = 0; z < 1; ++z)
    if (!std::isfinite(v12[z])) throw std::runtime_error("nonfinite TensorIR divide");
  std::vector<double> storage13(1);
  double* v13 = storage13.data();
  for (size_t z = 0; z < 1; ++z) v13[z] = v12[z] * v6[z];
  for (size_t z = 0; z < 1; ++z)
    if (!std::isfinite(v13[z])) throw std::runtime_error("nonfinite TensorIR multiply");
  std::vector<double> storage14(1);
  double* v14 = storage14.data();
  for (size_t q = 0; q < 1; ++q) {
    v14[0] += v13[q];
    if (!std::isfinite(v14[0])) throw std::runtime_error("nonfinite tensor reduction");
  }
  for (size_t z = 0; z < 1; ++z)
    if (!std::isfinite(v14[z])) throw std::runtime_error("nonfinite TensorIR reduce");
  std::vector<double> storage15(1);
  double* v15 = storage15.data();
  for (size_t z = 0; z < 1; ++z) v15[z] = (0x1.0000000000000p-2 * v14[z]);
  for (size_t z = 0; z < 1; ++z)
    if (!std::isfinite(v15[z])) throw std::runtime_error("nonfinite TensorIR add");
  std::copy_n(v15, 1, outputs[0]);
}

inline void ump2_run_beta_beta(double g, double x, double ei, double ej, double ea, double eb,
                               double* out) {
  const double* inputs[] = {&ej, &x, &g, &ea, &eb, &ei};
  double* outputs[] = {out};
  ump2_tile_beta_beta(inputs, outputs);
}
// TensorIR equation 90e184b88ef49d9965c5ea7e4c9c27174ea82d0060dfb3709b139b5209247288
inline void ump2_tile_alpha_beta(const double* const* inputs, double* const* outputs) {
  const double* v0 = inputs[0];
  if (!v0) throw std::invalid_argument("null tensor input");
  for (size_t z = 0; z < 1; ++z)
    if (!std::isfinite(v0[z])) throw std::runtime_error("nonfinite TensorIR input");
  const double* v1 = inputs[1];
  if (!v1) throw std::invalid_argument("null tensor input");
  for (size_t z = 0; z < 1; ++z)
    if (!std::isfinite(v1[z])) throw std::runtime_error("nonfinite TensorIR input");
  const double* v2 = inputs[2];
  if (!v2) throw std::invalid_argument("null tensor input");
  for (size_t z = 0; z < 1; ++z)
    if (!std::isfinite(v2[z])) throw std::runtime_error("nonfinite TensorIR input");
  const double* v3 = inputs[3];
  if (!v3) throw std::invalid_argument("null tensor input");
  for (size_t z = 0; z < 1; ++z)
    if (!std::isfinite(v3[z])) throw std::runtime_error("nonfinite TensorIR input");
  const double* v4 = inputs[4];
  if (!v4) throw std::invalid_argument("null tensor input");
  for (size_t z = 0; z < 1; ++z)
    if (!std::isfinite(v4[z])) throw std::runtime_error("nonfinite TensorIR input");
  std::vector<double> storage5(1);
  double* v5 = storage5.data();
  for (size_t z = 0; z < 1; ++z) v5[z] = v2[((z / 1) % 1) * 1];
  for (size_t z = 0; z < 1; ++z)
    if (!std::isfinite(v5[z])) throw std::runtime_error("nonfinite TensorIR broadcast");
  std::vector<double> storage6(1);
  double* v6 = storage6.data();
  for (size_t z = 0; z < 1; ++z) v6[z] = v3[((z / 1) % 1) * 1];
  for (size_t z = 0; z < 1; ++z)
    if (!std::isfinite(v6[z])) throw std::runtime_error("nonfinite TensorIR broadcast");
  std::vector<double> storage7(1);
  double* v7 = storage7.data();
  for (size_t z = 0; z < 1; ++z) v7[z] = v0[((z / 1) % 1) * 1];
  for (size_t z = 0; z < 1; ++z)
    if (!std::isfinite(v7[z])) throw std::runtime_error("nonfinite TensorIR broadcast");
  std::vector<double> storage8(1);
  double* v8 = storage8.data();
  for (size_t z = 0; z < 1; ++z) v8[z] = v1[((z / 1) % 1) * 1];
  for (size_t z = 0; z < 1; ++z)
    if (!std::isfinite(v8[z])) throw std::runtime_error("nonfinite TensorIR broadcast");
  std::vector<double> storage9(1);
  double* v9 = storage9.data();
  for (size_t z = 0; z < 1; ++z)
    v9[z] = (0x1.0000000000000p+0 * v5[z]) + (0x1.0000000000000p+0 * v7[z]) +
            (-0x1.0000000000000p+0 * v8[z]) + (-0x1.0000000000000p+0 * v6[z]);
  for (size_t z = 0; z < 1; ++z)
    if (!std::isfinite(v9[z])) throw std::runtime_error("nonfinite TensorIR add");
  std::vector<double> storage10(1);
  double* v10 = storage10.data();
  for (size_t z = 0; z < 1; ++z)
    if (v9[z] == 0) throw std::runtime_error("zero tensor denominator");
  for (size_t z = 0; z < 1; ++z) v10[z] = v4[z] / v9[z];
  for (size_t z = 0; z < 1; ++z)
    if (!std::isfinite(v10[z])) throw std::runtime_error("nonfinite TensorIR divide");
  std::vector<double> storage11(1);
  double* v11 = storage11.data();
  for (size_t z = 0; z < 1; ++z) v11[z] = v10[z] * v4[z];
  for (size_t z = 0; z < 1; ++z)
    if (!std::isfinite(v11[z])) throw std::runtime_error("nonfinite TensorIR multiply");
  std::vector<double> storage12(1);
  double* v12 = storage12.data();
  for (size_t q = 0; q < 1; ++q) {
    v12[0] += v11[q];
    if (!std::isfinite(v12[0])) throw std::runtime_error("nonfinite tensor reduction");
  }
  for (size_t z = 0; z < 1; ++z)
    if (!std::isfinite(v12[z])) throw std::runtime_error("nonfinite TensorIR reduce");
  std::copy_n(v12, 1, outputs[0]);
}

inline void ump2_run_alpha_beta(double g, double x, double ei, double ej, double ea, double eb,
                                double* out) {
  const double* inputs[] = {&ej, &ea, &ei, &eb, &g};
  double* outputs[] = {out};
  ump2_tile_alpha_beta(inputs, outputs);
}
inline Ump2CpuPlan ump2_cpu_plan(unsigned channel) {
  switch (channel) {
    case 0:
      return {ump2_run_alpha_alpha, 208ULL,
              "3941fc92696729f5febb65057fcfccdfd5b68f57115c2c3d9883f26a401f0356"};
    case 1:
      return {ump2_run_beta_beta, 208ULL,
              "615228b15a06c1219a3daf3e54a4a0ab5ebb50cb73c418745f057f33a47eeab7"};
    case 2:
      return {ump2_run_alpha_beta, 184ULL,
              "90e184b88ef49d9965c5ea7e4c9c27174ea82d0060dfb3709b139b5209247288"};
    default:
      throw std::invalid_argument("unknown UMP2 spin channel");
  }
}
inline constexpr char kUmp2InventoryHash[] =
    "190048e86fa6ec02441375120410b84987d7facbdbd393abc70f532154af236b";
}  // namespace generativeqc::mp2::generated
