"""Generated native curated semilocal metadata. Do not edit by hand."""

# Generated by tools/generate_native_semilocal_families.py from
# manifests/native_semilocal_families.json.

from typing import TypedDict


class _SemilocalFamilyFields(TypedDict):
    """Validated fields shared by all curated native semilocal families."""

    symbol: str
    code: int
    name: str
    scf_domain: str
    domain_version: int
    cuda_ks: bool
    requires_gradient: bool
    requires_tau: bool
    stationary_kernel: str
    stationary_ecp_gradient: bool
    components: tuple[tuple[str, str], ...]
    range_omega: str
    coefficient_policy: str
    exchange_policy: str


class _SemilocalFamilyRecord(_SemilocalFamilyFields, total=False):
    """Canonical method binding is present only for canonical exchange policy."""

    canonical_method: str


SEMILOCAL_FAMILIES: tuple[_SemilocalFamilyRecord, ...] = (
    {
        "symbol": "Lda",
        "code": 0,
        "name": "LDA",
        "scf_domain": "semilocal-scaled-v1/pbe-spin-c2-1e-18",
        "domain_version": 1,
        "cuda_ks": True,
        "requires_gradient": False,
        "requires_tau": False,
        "stationary_kernel": "lda",
        "stationary_ecp_gradient": True,
        "components": (
            ("LDA_X", "1"),
            ("LDA_C_PW", "1"),
        ),
        "range_omega": "0",
        "coefficient_policy": "exact",
        "exchange_policy": "none",
    },
    {
        "symbol": "Pbe",
        "code": 1,
        "name": "PBE",
        "scf_domain": "semilocal-scaled-v1/pbe-spin-c2-1e-18",
        "domain_version": 1,
        "cuda_ks": True,
        "requires_gradient": True,
        "requires_tau": False,
        "stationary_kernel": "pbe",
        "stationary_ecp_gradient": True,
        "components": (
            ("GGA_X_PBE", "1"),
            ("GGA_C_PBE", "1"),
        ),
        "range_omega": "0",
        "coefficient_policy": "native-scales",
        "exchange_policy": "any",
    },
    {
        "symbol": "R2scan",
        "code": 2,
        "name": "R2SCAN",
        "scf_domain": "semilocal-scaled-v1/pbe-spin-c2-1e-18",
        "domain_version": 1,
        "cuda_ks": True,
        "requires_gradient": True,
        "requires_tau": True,
        "stationary_kernel": "r2scan",
        "stationary_ecp_gradient": False,
        "components": (
            ("MGGA_X_R2SCAN", "1"),
            ("MGGA_C_R2SCAN", "1"),
        ),
        "range_omega": "0",
        "coefficient_policy": "exact",
        "exchange_policy": "none",
    },
    {
        "symbol": "B3lyp",
        "code": 3,
        "name": "B3LYP",
        "scf_domain": "b3lyp-vwn-rpa-tail-v1/density-vacuum-1e-18",
        "domain_version": 2,
        "cuda_ks": True,
        "requires_gradient": True,
        "requires_tau": False,
        "stationary_kernel": "composed",
        "stationary_ecp_gradient": True,
        "components": (
            ("LDA_X", "2/25"),
            ("GGA_X_B88", "18/25"),
            ("LDA_C_VWN_RPA", "19/100"),
            ("GGA_C_LYP", "81/100"),
        ),
        "range_omega": "0",
        "coefficient_policy": "exact",
        "exchange_policy": "any",
    },
    {
        "symbol": "Wb97mv",
        "code": 4,
        "name": "WB97M-V",
        "scf_domain": "libxc-7.0/work-mgga-v1/smooth-lr-a1.35-order16",
        "domain_version": 3,
        "cuda_ks": True,
        "requires_gradient": True,
        "requires_tau": True,
        "stationary_kernel": "wb97mv",
        "stationary_ecp_gradient": True,
        "components": (
            ("MGGA_X_WB97M_V", "1"),
            ("MGGA_C_WB97M_V", "1"),
        ),
        "range_omega": "3/10",
        "coefficient_policy": "exact",
        "exchange_policy": "canonical",
        "canonical_method": "WB97M-V",
    },
    {
        "symbol": "CamB3lyp",
        "code": 5,
        "name": "CAM-B3LYP",
        "scf_domain": "libxc-7.0.0/rsh-interior-v1",
        "domain_version": 5,
        "cuda_ks": False,
        "requires_gradient": True,
        "requires_tau": False,
        "stationary_kernel": "composed-interior",
        "stationary_ecp_gradient": False,
        "components": (
            ("GGA_X_B88", "7/20"),
            ("GGA_X_ITYH", "23/50"),
            ("LDA_C_VWN", "19/100"),
            ("GGA_C_LYP", "81/100"),
        ),
        "range_omega": "33/100",
        "coefficient_policy": "exact",
        "exchange_policy": "canonical",
        "canonical_method": "CAM-B3LYP",
    },
)

SEMILOCAL_FAMILY_CODES = frozenset(item["code"] for item in SEMILOCAL_FAMILIES)
SEMILOCAL_FAMILY_BY_CODE = {item["code"]: item for item in SEMILOCAL_FAMILIES}
SCF_DOMAIN_BY_VERSION = {
    1: "semilocal-scaled-v1/pbe-spin-c2-1e-18",
    2: "b3lyp-vwn-rpa-tail-v1/density-vacuum-1e-18",
    3: "libxc-7.0/work-mgga-v1/smooth-lr-a1.35-order16",
    5: "libxc-7.0.0/rsh-interior-v1",
}
