// Generated by tools/generate_method_manifest.py from manifests/public_methods.json.
// Native function pointers remain registry-owned; this file owns ABI/provider identity and
// capability facts.
#ifndef GENERATIVEQC_METHODS_GENERATED_METHOD_MANIFEST_HPP
#define GENERATIVEQC_METHODS_GENERATED_METHOD_MANIFEST_HPP

#include <array>
#include <cstdint>
#include <string_view>

#include "generativeqc/generativeqc.h"

// clang-format off
namespace generativeqc::methods::generated {

enum class PublicProvider : std::uint8_t { Reserved, Hf, Mp2, Rccsd, Rccsdt, Dft, Xtb };

struct MethodManifestEntry {
  std::string_view name;
  generativeqc_method method;
  generativeqc_method_family family;
  generativeqc_property_flags properties;
  bool supports_batch;
  PublicProvider provider;
  std::string_view unavailable_reason;
};

inline constexpr std::array<MethodManifestEntry, 13> kMethodManifest{{
    {"rhf", GENERATIVEQC_METHOD_RHF, GENERATIVEQC_METHOD_FAMILY_HARTREE_FOCK, GENERATIVEQC_PROPERTY_ENERGY | GENERATIVEQC_PROPERTY_FORCES, true, PublicProvider::Hf, ""},
    {"uhf", GENERATIVEQC_METHOD_UHF, GENERATIVEQC_METHOD_FAMILY_HARTREE_FOCK, GENERATIVEQC_PROPERTY_ENERGY | GENERATIVEQC_PROPERTY_FORCES, true, PublicProvider::Hf, ""},
    {"rccsd(t)", GENERATIVEQC_METHOD_RCCSD_T, GENERATIVEQC_METHOD_FAMILY_COUPLED_CLUSTER, GENERATIVEQC_PROPERTY_ENERGY | GENERATIVEQC_PROPERTY_FORCES, true, PublicProvider::Rccsdt, ""},
    {"mp2", GENERATIVEQC_METHOD_MP2, GENERATIVEQC_METHOD_FAMILY_PERTURBATION, GENERATIVEQC_PROPERTY_ENERGY | GENERATIVEQC_PROPERTY_FORCES, true, PublicProvider::Mp2, ""},
    {"lda-rks", GENERATIVEQC_METHOD_LDA_RKS, GENERATIVEQC_METHOD_FAMILY_DENSITY_FUNCTIONAL, GENERATIVEQC_PROPERTY_ENERGY, true, PublicProvider::Dft, ""},
    {"pbe-rks", GENERATIVEQC_METHOD_PBE_RKS, GENERATIVEQC_METHOD_FAMILY_DENSITY_FUNCTIONAL, GENERATIVEQC_PROPERTY_ENERGY, true, PublicProvider::Dft, ""},
    {"lda-uks", GENERATIVEQC_METHOD_LDA_UKS, GENERATIVEQC_METHOD_FAMILY_DENSITY_FUNCTIONAL, GENERATIVEQC_PROPERTY_ENERGY, true, PublicProvider::Dft, ""},
    {"pbe-uks", GENERATIVEQC_METHOD_PBE_UKS, GENERATIVEQC_METHOD_FAMILY_DENSITY_FUNCTIONAL, GENERATIVEQC_PROPERTY_ENERGY, true, PublicProvider::Dft, ""},
    {"r2scan-rks", GENERATIVEQC_METHOD_R2SCAN_RKS, GENERATIVEQC_METHOD_FAMILY_DENSITY_FUNCTIONAL, GENERATIVEQC_PROPERTY_ENERGY, true, PublicProvider::Dft, ""},
    {"r2scan-uks", GENERATIVEQC_METHOD_R2SCAN_UKS, GENERATIVEQC_METHOD_FAMILY_DENSITY_FUNCTIONAL, GENERATIVEQC_PROPERTY_ENERGY, true, PublicProvider::Dft, ""},
    {"rccsd", GENERATIVEQC_METHOD_RCCSD, GENERATIVEQC_METHOD_FAMILY_COUPLED_CLUSTER, GENERATIVEQC_PROPERTY_ENERGY | GENERATIVEQC_PROPERTY_FORCES, true, PublicProvider::Rccsd, ""},
    {"gfn2-xtb", GENERATIVEQC_METHOD_GFN2_XTB, GENERATIVEQC_METHOD_FAMILY_SEMIEMPIRICAL, GENERATIVEQC_PROPERTY_ENERGY | GENERATIVEQC_PROPERTY_FORCES, false, PublicProvider::Xtb, ""},
    {"pbe-d4-rks", GENERATIVEQC_METHOD_PBE_D4_RKS, GENERATIVEQC_METHOD_FAMILY_DENSITY_FUNCTIONAL, GENERATIVEQC_PROPERTY_ENERGY, true, PublicProvider::Dft, ""},
}};

inline constexpr const MethodManifestEntry* find_method(
    std::string_view name) noexcept {
  for (const auto& method : kMethodManifest)
    if (method.name == name) return &method;
  return nullptr;
}

inline constexpr const MethodManifestEntry* find_method(
    generativeqc_method value) noexcept {
  for (const auto& method : kMethodManifest)
    if (method.method == value) return &method;
  return nullptr;
}

}  // namespace generativeqc::methods::generated
// clang-format on

#endif
