"""Generated native curated semilocal metadata. Do not edit by hand."""

# Generated by tools/generate_native_semilocal_families.py from
# manifests/native_semilocal_families.json.

SEMILOCAL_FAMILIES = (
    {
        "symbol": "Lda",
        "code": 0,
        "name": "LDA",
        "scf_domain": "semilocal-scaled-v1/pbe-spin-c2-1e-18",
        "domain_version": 1,
        "cuda_ks": True,
        "components": (
            ("LDA_X", "1"),
            ("LDA_C_PW", "1"),
        ),
        "range_omega": "0",
        "coefficient_policy": "exact",
        "exchange_policy": "none",
    },
    {
        "symbol": "Pbe",
        "code": 1,
        "name": "PBE",
        "scf_domain": "semilocal-scaled-v1/pbe-spin-c2-1e-18",
        "domain_version": 1,
        "cuda_ks": True,
        "components": (
            ("GGA_X_PBE", "1"),
            ("GGA_C_PBE", "1"),
        ),
        "range_omega": "0",
        "coefficient_policy": "native-scales",
        "exchange_policy": "any",
    },
    {
        "symbol": "R2scan",
        "code": 2,
        "name": "R2SCAN",
        "scf_domain": "semilocal-scaled-v1/pbe-spin-c2-1e-18",
        "domain_version": 1,
        "cuda_ks": True,
        "components": (
            ("MGGA_X_R2SCAN", "1"),
            ("MGGA_C_R2SCAN", "1"),
        ),
        "range_omega": "0",
        "coefficient_policy": "exact",
        "exchange_policy": "none",
    },
    {
        "symbol": "B3lyp",
        "code": 3,
        "name": "B3LYP",
        "scf_domain": "b3lyp-vwn-rpa-tail-v1/density-vacuum-1e-18",
        "domain_version": 2,
        "cuda_ks": True,
        "components": (
            ("LDA_X", "2/25"),
            ("GGA_X_B88", "18/25"),
            ("LDA_C_VWN_RPA", "19/100"),
            ("GGA_C_LYP", "81/100"),
        ),
        "range_omega": "0",
        "coefficient_policy": "exact",
        "exchange_policy": "any",
    },
    {
        "symbol": "Wb97mv",
        "code": 4,
        "name": "WB97M-V",
        "scf_domain": "libxc-7.0/work-mgga-v1/smooth-lr-a1.35-order16",
        "domain_version": 3,
        "cuda_ks": True,
        "components": (
            ("MGGA_X_WB97M_V", "1"),
            ("MGGA_C_WB97M_V", "1"),
        ),
        "range_omega": "3/10",
        "coefficient_policy": "exact",
        "exchange_policy": "canonical",
        "canonical_method": "WB97M-V",
    },
)

SEMILOCAL_FAMILY_CODES = frozenset(item["code"] for item in SEMILOCAL_FAMILIES)
SCF_DOMAIN_BY_VERSION = {
    1: "semilocal-scaled-v1/pbe-spin-c2-1e-18",
    2: "b3lyp-vwn-rpa-tail-v1/density-vacuum-1e-18",
    3: "libxc-7.0/work-mgga-v1/smooth-lr-a1.35-order16",
}
