// Generated by tools/generate_method_manifest.py from manifests/public_methods.json.
// Do not edit by hand; ABI ids are explicit manifest data and must never be renumbered implicitly.
#ifndef GENERATIVEQC_GENERATED_METHOD_IDS_H
#define GENERATIVEQC_GENERATED_METHOD_IDS_H

#include <stdint.h>

// clang-format off
typedef int32_t generativeqc_method;
enum {
  GENERATIVEQC_METHOD_RHF = 1,
  GENERATIVEQC_METHOD_UHF = 2,
  GENERATIVEQC_METHOD_RCCSD_T = 4,
  GENERATIVEQC_METHOD_MP2 = 5,
  GENERATIVEQC_METHOD_LDA_RKS = 6,
  GENERATIVEQC_METHOD_PBE_RKS = 7,
  GENERATIVEQC_METHOD_LDA_UKS = 8,
  GENERATIVEQC_METHOD_PBE_UKS = 9,
  GENERATIVEQC_METHOD_R2SCAN_RKS = 10,
  GENERATIVEQC_METHOD_R2SCAN_UKS = 11,
  GENERATIVEQC_METHOD_RCCSD = 12,
  GENERATIVEQC_METHOD_GFN2_XTB = 15,
  GENERATIVEQC_METHOD_PBE_D4_RKS = 18
};
// clang-format on

#endif
