"""Generate shared CPU/CUDA GFN2 SCC energy composition from TensorIR."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "python"))

from generativeqc_compiler.method.gfn2_scc_free_energy_runtime import (
    GFN2_SCC_FREE_ENERGY_RUNTIME_VERSION,
    build_gfn2_component_energy_accumulate_program,
    build_gfn2_scc_free_energy_program,
    build_gfn2_scc_internal_energy_program,
)
from generativeqc_compiler.tensor.scalar_cpp import emit_scalar_cpp

_INTERNAL_INPUTS = (
    "core",
    "es2",
    "es3",
    "aes2",
    "spin",
    "d4_two_body",
    "explicit_point_charge",
    "electric_field",
    "periodic_embedding",
)
_FREE_INPUTS = ("electronic_temperature", "entropy", "internal_energy")
_COMPONENT_ACCUMULATE_INPUTS = ("current_energy", "component_energy")


def _host_device(source: str, function_name: str) -> str:
    return source.replace(
        f"inline bool {function_name}(",
        f"GENERATIVEQC_GFN2_SCC_FREE_ENERGY_HD inline bool {function_name}(",
        1,
    )


def native_header() -> str:
    internal = build_gfn2_scc_internal_energy_program()
    free = build_gfn2_scc_free_energy_program()
    component_accumulate = build_gfn2_component_energy_accumulate_program()
    internal_body = _host_device(
        emit_scalar_cpp(
            internal,
            function_name="compose_gfn2_scc_internal_energy",
            input_order=_INTERNAL_INPUTS,
            output_order=("internal_energy",),
        ),
        "compose_gfn2_scc_internal_energy",
    )
    free_body = _host_device(
        emit_scalar_cpp(
            free,
            function_name="compose_gfn2_scc_free_energy",
            input_order=_FREE_INPUTS,
            output_order=("free_energy",),
            fused_accumulation=True,
        ),
        "compose_gfn2_scc_free_energy",
    )
    component_accumulate_body = _host_device(
        emit_scalar_cpp(
            component_accumulate,
            function_name="accumulate_gfn2_component_energy",
            input_order=_COMPONENT_ACCUMULATE_INPUTS,
            output_order=("updated_energy",),
            ordered_native_sums=True,
        ),
        "accumulate_gfn2_component_energy",
    )
    return "\n".join(
        [
            "// Generated by tools/generate_gfn2_scc_free_energy_native.py from TensorIR; do not edit.",
            "#pragma once",
            "#include <cmath>",
            "#if defined(__CUDACC__)",
            "#define GENERATIVEQC_GFN2_SCC_FREE_ENERGY_HD __host__ __device__",
            "#else",
            "#define GENERATIVEQC_GFN2_SCC_FREE_ENERGY_HD",
            "#endif",
            "namespace generativeqc::xtb::generated {",
            f'inline constexpr const char* gfn2_scc_free_energy_runtime_version = "{GFN2_SCC_FREE_ENERGY_RUNTIME_VERSION}";',
            f'inline constexpr const char* gfn2_scc_internal_energy_hash = "{internal.logical_hash}";',
            f'inline constexpr const char* gfn2_scc_free_energy_hash = "{free.logical_hash}";',
            f'inline constexpr const char* gfn2_component_energy_accumulate_hash = "{component_accumulate.logical_hash}";',
            internal_body,
            free_body,
            component_accumulate_body,
            "}  // namespace generativeqc::xtb::generated",
            "#undef GENERATIVEQC_GFN2_SCC_FREE_ENERGY_HD",
            "",
        ]
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(native_header(), encoding="utf-8")


if __name__ == "__main__":
    main()
