"""Generate shared CPU/CUDA GFN2 external point-charge force helpers."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if __package__ in (None, ""):
    sys.path.insert(0, str(ROOT))
    sys.path.insert(0, str(ROOT / "python"))

from generativeqc_compiler.method.gfn2_external_point_charge_force import (
    GFN2_EXTERNAL_POINT_CHARGE_FORCE_VERSION,
    build_gfn2_external_point_charge_force_projection_program,
    build_gfn2_external_point_charge_force_weight_program,
    build_gfn2_external_point_charge_pair_primal,
    build_gfn2_external_point_charge_pair_vjp,
)
from generativeqc_compiler.tensor.optimize import prepare_for_backend
from generativeqc_compiler.tensor.scalar_cpp import emit_scalar_cpp


def _host_device(source: str) -> str:
    return source.replace(
        "inline bool ", "GENERATIVEQC_GFN2_EXTERNAL_PC_HD inline bool "
    ).replace("std::isfinite", "gfn2_external_pc_isfinite")


def native_header() -> str:
    primal = build_gfn2_external_point_charge_pair_primal()
    vjp = build_gfn2_external_point_charge_pair_vjp()
    weight = prepare_for_backend(
        build_gfn2_external_point_charge_force_weight_program(),
        backend="portable",
    )
    projection = prepare_for_backend(
        build_gfn2_external_point_charge_force_projection_program(),
        backend="portable",
    )
    weight_body = _host_device(
        emit_scalar_cpp(
            weight,
            function_name="gfn2_external_pc_force_weight_tensor",
            input_order=("kernel", "shell_charge", "point_charge"),
            output_order=("weight",),
        )
    )
    projection_body = _host_device(
        emit_scalar_cpp(
            projection,
            function_name="gfn2_external_pc_force_projection_tensor",
            input_order=("weight", "dx", "dy", "dz"),
            output_order=("fx", "fy", "fz"),
        )
    )
    return f"""// Generated by tools/generate_gfn2_external_point_charge_force.py from TensorIR + AD; do not edit.
#pragma once

#include <cmath>

#if defined(__CUDACC__)
#define GENERATIVEQC_GFN2_EXTERNAL_PC_HD __host__ __device__
#else
#define GENERATIVEQC_GFN2_EXTERNAL_PC_HD
#endif

namespace generativeqc::xtb::generated {{

inline constexpr const char* gfn2_external_point_charge_force_version =
    "{GFN2_EXTERNAL_POINT_CHARGE_FORCE_VERSION}";
inline constexpr const char* gfn2_external_point_charge_pair_primal_hash =
    "{primal.logical_hash}";
inline constexpr const char* gfn2_external_point_charge_pair_vjp_hash =
    "{vjp.derivative_hash}";
inline constexpr const char* gfn2_external_point_charge_force_weight_hash =
    "{weight.logical_hash}";
inline constexpr const char* gfn2_external_point_charge_force_projection_hash =
    "{projection.logical_hash}";

GENERATIVEQC_GFN2_EXTERNAL_PC_HD inline bool gfn2_external_pc_isfinite(
    double value) noexcept {{
#if defined(__CUDA_ARCH__)
  return isfinite(value);
#else
  return std::isfinite(value);
#endif
}}

{weight_body}
{projection_body}

GENERATIVEQC_GFN2_EXTERNAL_PC_HD inline bool evaluate_gfn2_external_point_charge_force(
    double kernel, double shell_charge, double point_charge,
    double dx, double dy, double dz,
    double& fx, double& fy, double& fz) noexcept {{
  double weight = 0.0;
  if (!gfn2_external_pc_force_weight_tensor(
          kernel, shell_charge, point_charge, weight)) return false;
  return gfn2_external_pc_force_projection_tensor(
      weight, dx, dy, dz, fx, fy, fz);
}}

}}  // namespace generativeqc::xtb::generated

#undef GENERATIVEQC_GFN2_EXTERNAL_PC_HD
"""


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(native_header(), encoding="utf-8")


if __name__ == "__main__":
    main()
