"""Generate the shared host/device VV10/rVV10 scalar pair family from TensorIR."""

from __future__ import annotations

import argparse
import sys
import types
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if __package__ in (None, ""):
    sys.path.insert(0, str(ROOT))
    sys.path.insert(0, str(ROOT / "python"))

# Follow the existing standalone TensorIR generators: no NumPy or runtime import.
import generativeqc_compiler

if __package__ in (None, ""):
    for package_name in ("tensor", "method"):
        qualified = f"generativeqc_compiler.{package_name}"
        if qualified not in sys.modules:
            package = types.ModuleType(qualified)
            package.__path__ = [
                str(ROOT / "python" / "generativeqc_compiler" / package_name)
            ]
            package.__package__ = qualified
            sys.modules[qualified] = package
            setattr(generativeqc_compiler, package_name, package)

from generativeqc_compiler.method.nonlocal_pair import (
    NONLOCAL_PAIR_LOWERING_VERSION,
    PAIR_INPUT_ORDER,
    PAIR_OUTPUT_ORDER,
    build_nonlocal_pair_program,
)
from generativeqc_compiler.tensor.scalar_cpp import emit_scalar_cpp


def native_header() -> str:
    """Emit each output closure once, shared unchanged by CPU and CUDA."""
    bodies, branches = [], []
    for variant, preconditioned in (("vv10", False), ("rvv10", False), ("rvv10", True)):
        for features in (False, True):
            for geometry in (False, True):
                program = build_nonlocal_pair_program(
                    variant,
                    preconditioned=preconditioned,
                    features=features,
                    geometry=geometry,
                )
                inputs = {
                    node.attrs["name"]
                    for node in program.live_nodes
                    if node.op == "input"
                }
                input_order = tuple(name for name in PAIR_INPUT_ORDER if name in inputs)
                output_order = tuple(
                    name for name in PAIR_OUTPUT_ORDER if name in program.outputs
                )
                name = f"pair_{variant}_{'prepared' if preconditioned else 'raw'}_f{int(features)}_g{int(geometry)}"
                body = emit_scalar_cpp(
                    program,
                    function_name=name,
                    input_order=input_order,
                    output_order=output_order,
                    caller_owned_checks=True,
                    ordered_native_sums=True,
                    output_dependency_order=True,
                )
                bodies.append(
                    f"// TensorIR logical hash: {program.logical_hash}\n"
                    + body.replace(
                        "inline bool ", "GENERATIVEQC_NONLOCAL_PAIR_HD inline bool ", 1
                    )
                )
                condition = f"Variant == Vv10Variant::{variant}"
                if variant == "rvv10":
                    condition += " && " + (
                        "Preconditioned" if preconditioned else "!Preconditioned"
                    )
                condition += " && " + ("Features" if features else "!Features")
                condition += " && " + ("Geometry" if geometry else "!Geometry")
                arguments = (
                    *input_order,
                    *(f"result.{output}" for output in output_order),
                )
                branches.append(
                    f"  if constexpr ({condition}) {{\n    {name}({', '.join(arguments)});\n  }}"
                )
    return (
        """// Generated by tools/generate_nonlocal_pair_native.py from TensorIR; do not edit.
#pragma once

#include <cmath>

#if defined(__CUDACC__)
#define GENERATIVEQC_NONLOCAL_PAIR_HD __host__ __device__
#else
#define GENERATIVEQC_NONLOCAL_PAIR_HD
#endif

// The runtime declares Vv10Variant before including this generated header.
namespace generativeqc::dft::nlc::generated {

"""
        + f'inline constexpr const char* nonlocal_pair_lowering_version = "{NONLOCAL_PAIR_LOWERING_VERSION}";\n'
        + """
struct PairValues {
  double phi{};
  double dphi_domega{};
  double dphi_dkappa{};
  double dphi_dr2{};
};

"""
        + "\n".join(bodies)
        + """
template <Vv10Variant Variant, bool Features, bool Geometry, bool Preconditioned = false>
GENERATIVEQC_NONLOCAL_PAIR_HD inline PairValues pair_values(
    double r2, double wi, double wj, double ki, double kj,
    double row_inverse_kappa = 0.0) noexcept {
  static_assert(Variant == Vv10Variant::vv10 || Variant == Vv10Variant::rvv10);
  PairValues result{};
"""
        + "\n".join(branches)
        + """
  return result;
}

}  // namespace generativeqc::dft::nlc::generated

#undef GENERATIVEQC_NONLOCAL_PAIR_HD
"""
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(native_header(), encoding="utf-8")


if __name__ == "__main__":
    main()
