"""Generate the Python-free native CLI basis catalog from the bundled BSE subset."""

from __future__ import annotations

import argparse
import json
import math
from pathlib import Path


def _number(value: object, *, positive: bool, label: str) -> str:
    if not isinstance(value, (str, int, float)) or isinstance(value, bool):
        raise TypeError(f"{label} must be a decimal scalar")
    text = str(value)
    number = float(text)
    if not math.isfinite(number) or (positive and number <= 0.0):
        raise ValueError(f"invalid {label}: {value!r}")
    return text


def load_pack(
    path: Path,
) -> list[tuple[str, list[tuple[int, int, list[tuple[str, str]]]]]]:
    payload = json.loads(path.read_text(encoding="utf-8"))
    if payload.get("schema_version") != 1 or not isinstance(payload.get("bases"), dict):
        raise ValueError("unsupported bundled basis-pack schema")

    result = []
    for name, basis in sorted(payload["bases"].items()):
        if not isinstance(name, str) or not name or name != name.lower():
            raise ValueError("basis names must be non-empty lowercase strings")
        elements = basis.get("elements") if isinstance(basis, dict) else None
        if not isinstance(elements, dict) or not elements:
            raise ValueError(f"{name}: basis requires element records")
        rows = []
        for atomic_text, shells in sorted(
            elements.items(), key=lambda item: int(item[0])
        ):
            atomic_number = int(atomic_text)
            if (
                not 1 <= atomic_number <= 118
                or not isinstance(shells, list)
                or not shells
            ):
                raise ValueError(f"{name}: invalid element record {atomic_text!r}")
            for shell in shells:
                if not isinstance(shell, dict):
                    raise TypeError(f"{name}: shell must be an object")
                angular = shell.get("angular_momentum")
                exponents = shell.get("exponents")
                coefficients = shell.get("coefficients")
                if (
                    not isinstance(angular, int)
                    or isinstance(angular, bool)
                    or angular < 0
                    or not isinstance(exponents, list)
                    or not isinstance(coefficients, list)
                    or not exponents
                    or len(exponents) != len(coefficients)
                ):
                    raise ValueError(f"{name}: malformed shell for Z={atomic_number}")
                primitives = [
                    (
                        _number(exponent, positive=True, label="basis exponent"),
                        _number(coefficient, positive=False, label="basis coefficient"),
                    )
                    for exponent, coefficient in zip(
                        exponents, coefficients, strict=True
                    )
                ]
                rows.append((atomic_number, angular, primitives))
        result.append((name, rows))
    return result


def emit(pack: list[tuple[str, list[tuple[int, int, list[tuple[str, str]]]]]]) -> str:
    primitives: list[tuple[str, str]] = []
    shells: list[tuple[int, int, int, int]] = []
    bases: list[tuple[str, int, int]] = []

    for name, rows in pack:
        shell_offset = len(shells)
        for atomic_number, angular, shell_primitives in rows:
            primitive_offset = len(primitives)
            primitives.extend(shell_primitives)
            shells.append(
                (atomic_number, angular, primitive_offset, len(shell_primitives))
            )
        bases.append((name, shell_offset, len(rows)))

    lines = [
        "// Generated by tools/generate_cli_basis_pack.py from python/generativeqc/data/basis_pack.json.",
        "// Build-time Python converts audited data to C++ constants; the installed CLI reads no JSON.",
        "#ifndef GENERATIVEQC_CLI_BASIS_PACK_HPP",
        "#define GENERATIVEQC_CLI_BASIS_PACK_HPP",
        "",
        "#include <array>",
        "#include <cstdint>",
        "#include <string_view>",
        "",
        "namespace generativeqc::cli::basis_generated {",
        "",
        "struct PrimitiveRow { double exponent; double coefficient; };",
        "struct ShellRow {",
        "  std::int32_t atomic_number;",
        "  std::uint32_t angular_momentum;",
        "  std::uint32_t primitive_offset;",
        "  std::uint32_t primitive_count;",
        "};",
        "struct BasisRow {",
        "  std::string_view name;",
        "  std::uint32_t shell_offset;",
        "  std::uint32_t shell_count;",
        "};",
        "",
        f"inline constexpr std::array<PrimitiveRow, {len(primitives)}> kPrimitives{{{{",
    ]
    lines.extend(
        f"    {{{exponent}, {coefficient}}}," for exponent, coefficient in primitives
    )
    lines.extend(
        [
            "}};",
            "",
            f"inline constexpr std::array<ShellRow, {len(shells)}> kShells{{{{",
        ]
    )
    lines.extend(
        f"    {{{atomic_number}, {angular}u, {offset}u, {count}u}},"
        for atomic_number, angular, offset, count in shells
    )
    lines.extend(
        [
            "}};",
            "",
            f"inline constexpr std::array<BasisRow, {len(bases)}> kBases{{{{",
        ]
    )
    lines.extend(
        f'    {{"{name}", {offset}u, {count}u}},' for name, offset, count in bases
    )
    lines.extend(
        [
            "}};",
            "",
            "}  // namespace generativeqc::cli::basis_generated",
            "",
            "#endif",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    text = emit(load_pack(args.input))
    args.output.parent.mkdir(parents=True, exist_ok=True)
    if not args.output.exists() or args.output.read_text(encoding="utf-8") != text:
        args.output.write_text(text, encoding="utf-8")


if __name__ == "__main__":
    main()
